@echo off
title Swift.xyz
:menu
cls
echo Welcome to Swift.xyz
echo
echo 1. Run Debloater
echo 2. Github
set /p choice="Option:"
if "%choice%"=="1" goto debloater
if "%choice%"=="2" start https://github.com/Zep194/Swift.xyz & exit
goto menu

:debloater
echo Removing Shit Applications...
powershell -Command "Get-AppxPackage Clipchamp.Clipchamp | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Microsoft.3DBuilder | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Microsoft.549981C3F5F10 | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Microsoft.BingFinance | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Microsoft.BingFoodAndDrink | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Microsoft.BingHealthAndFitness | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Microsoft.BingNews | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Microsoft.BingSports | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Microsoft.BingTranslator | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Microsoft.BingTravel | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Microsoft.BingWeather | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Microsoft.Getstarted | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Microsoft.Messaging | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Microsoft.Microsoft3DViewer | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Microsoft.MicrosoftJournal | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Microsoft.MicrosoftOfficeHub | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Microsoft.MicrosoftPowerBIForWindows | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Microsoft.MicrosoftSolitaireCollection | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Microsoft.MicrosoftStickyNotes | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Microsoft.MixedReality.Portal | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Microsoft.NetworkSpeedTest | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Microsoft.News | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Microsoft.Office.OneNote | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Microsoft.Office.Sway | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Microsoft.OneConnect | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Microsoft.Print3D | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Microsoft.SkypeApp | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Microsoft.Todos | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Microsoft.WindowsAlarms | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Microsoft.WindowsFeedbackHub | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Microsoft.WindowsMaps | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Microsoft.WindowsSoundRecorder | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Microsoft.XboxApp | Remove-AppxPackage"
powershell -Command "Get-AppxPackage MicrosoftCorporationII.MicrosoftFamily | Remove-AppxPackage"
powershell -Command "Get-AppxPackage MicrosoftCorporationII.QuickAssist | Remove-AppxPackage"
powershell -Command "Get-AppxPackage MicrosoftTeams | Remove-AppxPackage"
powershell -Command "Get-AppxPackage MSTeams | Remove-AppxPackage"
powershell -Command "Get-AppxPackage ACGMediaPlayer | Remove-AppxPackage"
powershell -Command "Get-AppxPackage ActiproSoftwareLLC | Remove-AppxPackage"
powershell -Command "Get-AppxPackage AdobeSystemsIncorporated.AdobePhotoshopExpress | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Amazon.com.Amazon | Remove-AppxPackage"
powershell -Command "Get-AppxPackage AmazonVideo.PrimeVideo | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Asphalt8Airborne | Remove-AppxPackage"
powershell -Command "Get-AppxPackage AutodeskSketchBook | Remove-AppxPackage"
powershell -Command "Get-AppxPackage CaesarsSlotsFreeCasino | Remove-AppxPackage"
powershell -Command "Get-AppxPackage COOKINGFEVER | Remove-AppxPackage"
powershell -Command "Get-AppxPackage CyberLinkMediaSuiteEssentials | Remove-AppxPackage"
powershell -Command "Get-AppxPackage DisneyMagicKingdoms | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Disney | Remove-AppxPackage"
powershell -Command "Get-AppxPackage DrawboardPDF | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Duolingo-LearnLanguagesforFree | Remove-AppxPackage"
powershell -Command "Get-AppxPackage EclipseManager | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Facebook | Remove-AppxPackage"
powershell -Command "Get-AppxPackage FarmVille2CountryEscape | Remove-AppxPackage"
powershell -Command "Get-AppxPackage fitbit | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Flipboard | Remove-AppxPackage"
powershell -Command "Get-AppxPackage HiddenCity | Remove-AppxPackage"
powershell -Command "Get-AppxPackage HULULLC.HULUPLUS | Remove-AppxPackage"
powershell -Command "Get-AppxPackage iHeartRadio | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Instagram | Remove-AppxPackage"
powershell -Command "Get-AppxPackage king.com.BubbleWitch3Saga | Remove-AppxPackage"
powershell -Command "Get-AppxPackage king.com.CandyCrushSaga | Remove-AppxPackage"
powershell -Command "Get-AppxPackage king.com.CandyCrushSodaSaga | Remove-AppxPackage"
powershell -Command "Get-AppxPackage LinkedInforWindows | Remove-AppxPackage"
powershell -Command "Get-AppxPackage MarchofEmpires | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Netflix | Remove-AppxPackage"
powershell -Command "Get-AppxPackage NYTCrossword | Remove-AppxPackage"
powershell -Command "Get-AppxPackage OneCalendar | Remove-AppxPackage"
powershell -Command "Get-AppxPackage PandoraMediaInc | Remove-AppxPackage"
powershell -Command "Get-AppxPackage PhototasticCollage | Remove-AppxPackage"
powershell -Command "Get-AppxPackage PicsArt-PhotoStudio | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Plex | Remove-AppxPackage"
powershell -Command "Get-AppxPackage PolarrPhotoEditorAcademicEdition | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Royal Revolt | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Shazam | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Sidia.LiveWallpaper | Remove-AppxPackage"
powershell -Command "Get-AppxPackage SlingTV | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Spotify | Remove-AppxPackage"
powershell -Command "Get-AppxPackage TikTok | Remove-AppxPackage"
powershell -Command "Get-AppxPackage TuneInRadio | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Twitter | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Viber | Remove-AppxPackage"
powershell -Command "Get-AppxPackage WinZipUniversal | Remove-AppxPackage"
powershell -Command "Get-AppxPackage Wunderlist | Remove-AppxPackage"
powershell -Command "Get-AppxPackage XING | Remove-AppxPackage"
echo.
echo Debloater completed. Press any key to exit.
pause >nul
exit
